"""Write the What's new history into the addon from the commit log.

python tools/whatsnew/build.py [--versions 5] [--next 8.2.0]

Reads the release tags (newest first) and, for each of the last N versions, the player-facing
commit subjects between that tag and the one before it: `new:` lines, `improved:` lines and a count
of `fixes:` commits. Commit subjects are already written for players (see CLAUDE.md), so they are
used as they are, minus the prefix.

--next adds the commits after the newest tag as that upcoming version, for testing a release
before it is tagged. CI runs this on the tag being released, so the tag itself is the newest.

Output: Core/WhatsNew/Changelog.lua (committed, so the addon always has a history to show).
"""

import argparse
import datetime
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, 'Core', 'WhatsNew', 'Changelog.lua')

KINDS = [
    ('new', re.compile(r'^(new|feat|feature):\s*', re.I)),
    ('improved', re.compile(r'^(improved|perf):\s*', re.I)),
]
FIX = re.compile(r'^(fix|fixes|bug):\s*', re.I)
VERSION = re.compile(r'^\d+(\.\d+)*$')


def git(*args):
    return subprocess.run(['git', *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout


def version_key(tag):
    return tuple(int(part) for part in tag.split('.'))


def lua_string(text):
    text = text.replace('\\', '\\\\')
    # Single quotes unless the text has an apostrophe and no double quote (what StyLua picks)
    if "'" in text and '"' not in text:
        return '"' + text + '"'
    return "'" + text.replace("'", "\\'") + "'"


def collect(rev_range):
    lines, fixes, seen = [], 0, set()
    for subject in git('log', '--no-merges', '--format=%s', rev_range).splitlines():
        subject = subject.strip()
        if FIX.match(subject):
            fixes += 1
            continue
        for kind, pattern in KINDS:
            if pattern.match(subject):
                text = pattern.sub('', subject).strip()
                text = text[:1].upper() + text[1:]
                if text and text not in seen:
                    seen.add(text)
                    lines.append((kind, text))
                break
    # New features first, then improvements, each in the order they landed
    lines.reverse()
    lines.sort(key=lambda line: 0 if line[0] == 'new' else 1)
    return lines, fixes


def tag_date(tag):
    stamp = git('log', '-1', '--format=%cI', tag).strip()
    return datetime.datetime.fromisoformat(stamp).strftime('%B %Y')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--versions', type=int, default=5)
    parser.add_argument('--next', help='include commits after the newest tag as this version')
    args = parser.parse_args()

    tags = sorted((t for t in git('tag').split() if VERSION.match(t)), key=version_key, reverse=True)
    releases = []
    if args.next and tags:
        releases.append((args.next, tags[0] + '..HEAD', datetime.date.today().strftime('%B %Y')))
    for i, tag in enumerate(tags):
        if len(releases) >= args.versions:
            break
        previous = tags[i + 1] if i + 1 < len(tags) else None
        rev_range = (previous + '..' + tag) if previous else tag
        releases.append((tag, rev_range, tag_date(tag)))

    out = [
        '-- Generated by tools/whatsnew/build.py from the commit history. Do not edit by hand:',
        '-- run the script (CI runs it on every release). Heroes live in Heroes.lua.',
        '---@class SUI',
        'local SUI = SUI',
        '',
        '---@type {version: string, date: string, fixes: number, lines: {kind: string, text: string}[]}[]',
        'SUI.Changelog = {',
    ]
    for version, rev_range, date in releases:
        lines, fixes = collect(rev_range)
        if not lines and not fixes:
            continue
        out.append('\t{')
        out.append('\t\tversion = %s,' % lua_string(version))
        out.append('\t\tdate = %s,' % lua_string(date))
        out.append('\t\tfixes = %d,' % fixes)
        if lines:
            out.append('\t\tlines = {')
            for kind, text in lines:
                out.append('\t\t\t{ kind = %s, text = %s },' % (lua_string(kind), lua_string(text)))
            out.append('\t\t},')
        else:
            out.append('\t\tlines = {},')
        out.append('\t},')
    out.append('}')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(out) + '\n')
    print(OUT, len(releases), 'versions')


if __name__ == '__main__':
    main()
