addon-name: "SpartanUI"
addon-description: "a comprehensive UI overhaul addon"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/spartan-ui"
  wago: "https://addons.wago.io/addons/vEGPqeN1"
  discord: "https://discord.gg/Qc9TRBv"
  roadmap: "https://github.com/orgs/spartanui-wow/projects/1"
